name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Check baseurl
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "BASE_URL=$baseurl" >> $GITHUB_ENV
          fi

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b

      # - name: Test Site
      #   run: |
      #     bash tools/test.sh

      - name: Deploy
        run: |
          bash tools/deploy.sh
